/**
 * Render a Homebrew formula for a released `beeptui` binary. Pure string
 * construction so it's unit-testable; the release workflow fills in the real
 * per-target SHA-256s (from `sha256sums.txt`) and pushes the result to the tap.
 *
 * The formula installs the prebuilt, per-OS standalone binary (built by
 * `bun build --compile` on native runners — OpenTUI's renderer is
 * platform-specific), not a from-source build, so no Bun is needed at install
 * time.
 */

export interface FormulaInputs {
  /** Release version without the leading `v` (e.g. `1.2.0`). */
  version: string
  /** `owner/repo` the release lives in (e.g. `mitchmalone/beeptui`). */
  repo: string
  /** SHA-256 of the `beeptui-darwin-arm64` release asset. */
  darwinArm64Sha256: string
  /** SHA-256 of the `beeptui-linux-x64` release asset. */
  linuxX64Sha256: string
}

const HEX64 = /^[0-9a-f]{64}$/

function assertSha(label: string, value: string): void {
  if (!HEX64.test(value)) {
    throw new Error(`${label} must be a 64-char lowercase hex SHA-256, got: ${value}`)
  }
}

/** Build the `beeptui.rb` formula text for the given release. */
export function renderFormula(inputs: FormulaInputs): string {
  const { version, repo, darwinArm64Sha256, linuxX64Sha256 } = inputs
  if (!/^\d+\.\d+\.\d+/.test(version)) {
    throw new Error(`version must be a semver like 1.2.0, got: ${version}`)
  }
  if (!/^[\w.-]+\/[\w.-]+$/.test(repo)) throw new Error(`repo must be owner/repo, got: ${repo}`)
  assertSha('darwinArm64Sha256', darwinArm64Sha256)
  assertSha('linuxX64Sha256', linuxX64Sha256)

  const base = `https://github.com/${repo}/releases/download/v${version}`
  return `# typed: false
# frozen_string_literal: true

# Homebrew formula for beeptui. Generated by src/packaging/homebrew.ts on
# release — do not edit by hand.
class Beeptui < Formula
  desc "Keyboard-first terminal client for Beeper"
  homepage "https://github.com/${repo}"
  version "${version}"
  license "MIT"

  on_macos do
    on_arm do
      url "${base}/beeptui-darwin-arm64"
      sha256 "${darwinArm64Sha256}"

      def install
        bin.install "beeptui-darwin-arm64" => "beeptui"
      end
    end
  end

  on_linux do
    on_intel do
      url "${base}/beeptui-linux-x64"
      sha256 "${linuxX64Sha256}"

      def install
        bin.install "beeptui-linux-x64" => "beeptui"
      end
    end
  end

  test do
    assert_match "beeptui", shell_output("#{bin}/beeptui --version")
  end
end
`
}

// CLI entry for the release workflow: reads inputs from the environment and
// prints the formula to stdout. Kept off the import path of the app.
if (import.meta.main) {
  const env = process.env
  const formula = renderFormula({
    version: (env.FORMULA_VERSION ?? '').replace(/^v/, ''),
    repo: env.FORMULA_REPO ?? '',
    darwinArm64Sha256: env.FORMULA_SHA_DARWIN_ARM64 ?? '',
    linuxX64Sha256: env.FORMULA_SHA_LINUX_X64 ?? '',
  })
  process.stdout.write(formula)
}
